name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Decode service account
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MT_PROD }}" > "${HOME}/gcp-key.json"

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MT_PROD }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Set GCP project
      run: gcloud config set project mt-prod-30347

    - name: Install dependencies
      run: npm install
      working-directory: ./functions

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: firebase deploy --only functions --project mt-prod-30347